# Generated by Django 4.0.1 on 2022-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletinfo',
            name='tlocation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
