# Generated by Django 4.0.1 on 2022-01-28 10:51

import _operator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_toiletinfo_tlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletinfo',
            name='tname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='toiletinfo',
            name='tnumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='toiletinfo',
            name='topen',
            field=models.CharField(max_length=200, null=_operator.truediv),
        ),
    ]
