# Generated by Django 4.0.1 on 2022-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_toiletinfo_tname_alter_toiletinfo_tnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toiletinfo',
            name='tbidget',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='toiletinfo',
            name='tpaper',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='toiletinfo',
            name='tpassword',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='toiletinfo',
            name='tpublic',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='toiletinfo',
            name='ttype',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='toiletinfo',
            name='topen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
