# Generated by Django 4.0.1 on 2022-01-28 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200, null=True)),
                ('tlocation', models.CharField(max_length=300, null=True)),
                ('tnumber', models.CharField(max_length=200, null=True)),
                ('topen', models.CharField(max_length=200, null=True)),
                ('tbidget', models.BooleanField(null=True)),
                ('tpaper', models.BooleanField(null=True)),
                ('tpassword', models.BooleanField(null=True)),
                ('tpublic', models.BooleanField(null=True)),
                ('ttype', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
