# Generated by Django 4.0.1 on 2022-02-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToiletInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200, null=True)),
                ('tlocation', models.CharField(max_length=300, null=True)),
                ('tlat', models.FloatField()),
                ('tlong', models.FloatField()),
                ('tnumber', models.CharField(max_length=200, null=True)),
                ('topen', models.CharField(max_length=200, null=True)),
                ('tbidget', models.BooleanField(null=True)),
                ('tpaper', models.BooleanField(null=True)),
                ('tpassword', models.BooleanField(null=True)),
                ('tpublic', models.BooleanField(null=True)),
                ('ttype', models.IntegerField(blank=True, choices=[(0, '푸세식'), (1, '좌변식')], default=3, null=True)),
            ],
        ),
    ]
