# Generated by Django 4.0.1 on 2022-02-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletinfo',
            name='tlat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='toiletinfo',
            name='tlong',
            field=models.FloatField(null=True),
        ),
    ]
